"""Phase 2.5 — Write Gemini suggestions to review output files.

All outputs are REVIEW-ONLY — nothing is auto-promoted to config.

Output files (written to --output-dir):
  group_aliases_suggested.yaml    Candidate additions for group_aliases.yaml
  reference_resolutions.jsonl     Near-text reference resolutions
  preference_enrichments.jsonl    Structured preference extractions
  subsection_resolutions.jsonl    Row / spot-ID suggestions
  gemini_run_summary.json         Metadata and error log
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from typing import List

import yaml

from saronsdal.llm.schemas import GeminiRunSummary, GroupSuggestion

logger = logging.getLogger(__name__)

_HEADER = """\
# ==============================================================
# REVIEW BEFORE PROMOTING
# Generated by Phase 2.5 LLM enrichment — saronsdal.cli.llm_enrich
# Run:       {run_time}
# Model:     {model}
# Processed: {processed} candidates  |  Errors: {errors}
# ==============================================================

"""


def write_suggestions(output_dir: Path, run: GeminiRunSummary) -> None:
    """Write all suggestion files to output_dir (created if absent)."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    run_time = datetime.now().isoformat(timespec="seconds")
    header = _HEADER.format(
        run_time=run_time,
        model=run.model_used,
        processed=run.candidates_processed,
        errors=len(run.errors),
    )

    _write_group_aliases_yaml(output_dir, run.group_suggestions, header)
    _write_jsonl(
        output_dir, "reference_resolutions.jsonl",
        [asdict(s) for s in run.near_text_suggestions],
    )
    _write_jsonl(
        output_dir, "preference_enrichments.jsonl",
        [asdict(s) for s in run.preference_suggestions],
    )
    _write_jsonl(
        output_dir, "subsection_resolutions.jsonl",
        [asdict(s) for s in run.subsection_suggestions],
    )
    _write_run_summary(output_dir, run, run_time)

    logger.info(
        "Suggestions written to %s  "
        "(group=%d  near_text=%d  prefs=%d  subsec=%d  errors=%d)",
        output_dir,
        len(run.group_suggestions), len(run.near_text_suggestions),
        len(run.preference_suggestions), len(run.subsection_suggestions),
        len(run.errors),
    )


# ---------------------------------------------------------------------------
# group_aliases_suggested.yaml
# ---------------------------------------------------------------------------

def _write_group_aliases_yaml(
    output_dir: Path,
    suggestions: List[GroupSuggestion],
    header: str,
) -> None:
    new_groups = [
        s for s in suggestions
        if s.classification in ("new_group_alias", "known_group_variant")
        and s.suggested_canonical
    ]
    place_aliases = [
        s for s in suggestions
        if s.classification == "place_name" and s.suggested_canonical
    ]

    doc: dict = {}
    if new_groups:
        orgs: dict = {}
        for s in new_groups:
            key = _yaml_key(s.suggested_canonical or s.phrase)
            orgs[key] = {
                "canonical": s.suggested_canonical,
                "aliases": sorted(set(s.raw_variants + ([s.suggested_canonical]
                                                        if s.suggested_canonical else []))),
                "_classification": s.classification,
                "_confidence": round(s.confidence, 3),
                "_reasoning": s.reasoning,
                "_booking_nos": s.booking_nos,
            }
        doc["new_organizations"] = orgs

    if place_aliases:
        places: dict = {}
        for s in place_aliases:
            key = _yaml_key(s.suggested_canonical or s.phrase)
            places[key] = {
                "canonical": s.suggested_canonical,
                "aliases": sorted(set(s.raw_variants)),
                "_confidence": round(s.confidence, 3),
                "_reasoning": s.reasoning,
                "_booking_nos": s.booking_nos,
            }
        doc["possible_place_aliases"] = places

    path = output_dir / "group_aliases_suggested.yaml"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(header)
        if doc:
            yaml.dump(doc, fh, allow_unicode=True, default_flow_style=False,
                      sort_keys=False)
        else:
            fh.write("# No new group alias suggestions from this run.\n")
    logger.info("Wrote %s (%d new groups, %d place aliases)",
                path.name, len(new_groups), len(place_aliases))


# ---------------------------------------------------------------------------
# JSONL writers
# ---------------------------------------------------------------------------

def _write_jsonl(output_dir: Path, filename: str, records: List[dict]) -> None:
    path = output_dir / filename
    with open(path, "w", encoding="utf-8") as fh:
        for rec in records:
            fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
    logger.info("Wrote %s (%d records)", path.name, len(records))


def _write_run_summary(
    output_dir: Path, run: GeminiRunSummary, run_time: str
) -> None:
    summary = {
        "run_time": run_time,
        "model_used": run.model_used,
        "candidates_processed": run.candidates_processed,
        "candidates_capped": run.candidates_capped,
        "results": {
            "group_suggestions": len(run.group_suggestions),
            "near_text_suggestions": len(run.near_text_suggestions),
            "preference_suggestions": len(run.preference_suggestions),
            "subsection_suggestions": len(run.subsection_suggestions),
        },
        "errors": run.errors,
    }
    path = output_dir / "gemini_run_summary.json"
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(summary, fh, ensure_ascii=False, indent=2)
    logger.info("Wrote %s", path.name)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _yaml_key(name: str) -> str:
    """Convert a canonical name to a compact snake_case YAML key."""
    key = name.lower()
    for no, rep in [("æ", "ae"), ("ø", "oe"), ("å", "aa")]:
        key = key.replace(no, rep)
    key = "".join(c if c.isalnum() else "_" for c in key)
    while "__" in key:
        key = key.replace("__", "_")
    return key.strip("_")
